language: python
python:
    - "2.7"

# Cache PlatformIO packages
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/OneshotUpdateTest
    - PLATFORMIO_CI_SRC=examples/ReadTemperature
    - PLATFORMIO_CI_SRC=examples/ReinstallAddressTest
    - PLATFORMIO_CI_SRC=examples/ShutdownTest

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --project-conf=platformio.ini

